package test.app.project.vo;

import java.sql.Date;

/**
 * 예약테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BookingTableVo {


	/** 예약번호. */
	private int booking_num;

	/** 객실정보. */
	private int room_num;

	/** 회원테이블. */
	private String mid;

	/** 결제금액. */
	private int pay_money;

	/** 예약신청날짜. */
	private java.sql.Date books_date;

	/** 숙박시작일. */
	private String start_date;

	/** 숙박종료일. */
	private String end_date;

	/** 예약상태. */
	private String bookStatus;
	
	private String name;


	/**
	 * 생성자.
	 */
	public BookingTableVo() {
	}


	public BookingTableVo(int booking_num, int room_num, String mid, int pay_money, Date books_date, String start_date,
			String end_date, String bookStatus, String name) {
		super();
		this.booking_num = booking_num;
		this.room_num = room_num;
		this.mid = mid;
		this.pay_money = pay_money;
		this.books_date = books_date;
		this.start_date = start_date;
		this.end_date = end_date;
		this.bookStatus = bookStatus;
		this.name = name;
	}


	public int getBooking_num() {
		return booking_num;
	}


	public void setBooking_num(int booking_num) {
		this.booking_num = booking_num;
	}


	public int getRoom_num() {
		return room_num;
	}


	public void setRoom_num(int room_num) {
		this.room_num = room_num;
	}


	public String getMid() {
		return mid;
	}


	public void setMid(String mid) {
		this.mid = mid;
	}


	public int getPay_money() {
		return pay_money;
	}


	public void setPay_money(int pay_money) {
		this.pay_money = pay_money;
	}


	public java.sql.Date getBooks_date() {
		return books_date;
	}


	public void setBooks_date(java.sql.Date books_date) {
		this.books_date = books_date;
	}


	public String getStart_date() {
		return start_date;
	}


	public void setStart_date(String start_date) {
		this.start_date = start_date;
	}


	public String getEnd_date() {
		return end_date;
	}


	public void setEnd_date(String end_date) {
		this.end_date = end_date;
	}


	public String getBookStatus() {
		return bookStatus;
	}


	public void setBookStatus(String bookStatus) {
		this.bookStatus = bookStatus;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}



}
