package test.app.project.vo;

/**
 * 이벤트 이미지 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EventimagesVo {

	/** 이미지식별키. */
	private int eimgnum;

	/** 원본파일명. */
	private String orgfilename;

	/** 저장파일명. */
	private String savefilename;

	private int event_Num;

	/**
	 * 생성자.
	 */
	public EventimagesVo() {
	}

	public EventimagesVo(int eimgnum, String orgfilename, String savefilename, int event_Num) {
		super();
		this.eimgnum = eimgnum;
		this.orgfilename = orgfilename;
		this.savefilename = savefilename;
		this.event_Num = event_Num;
	}

	public int getEimgnum() {
		return eimgnum;
	}

	public void setEimgnum(int eimgnum) {
		this.eimgnum = eimgnum;
	}

	public String getOrgfilename() {
		return orgfilename;
	}

	public void setOrgfilename(String orgfilename) {
		this.orgfilename = orgfilename;
	}

	public String getSavefilename() {
		return savefilename;
	}

	public void setSavefilename(String savefilename) {
		this.savefilename = savefilename;
	}

	public int getEvent_Num() {
		return event_Num;
	}

	public void setEvent_Num(int event_Num) {
		this.event_Num = event_Num;
	}

}
