package test.app.project.vo;

import java.sql.Date;

/**
 * �쉶�썝�뀒�씠釉� 紐⑤뜽 �겢�옒�뒪.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MembersVo{


	/** �쉶�썝�븘�씠�뵒. */
	private String mid;

	/** �쉶�썝�벑湲됲뀒�씠釉�. */
	private int gnum;

	/** 鍮꾨�踰덊샇. */
	private String mpwd;

	/** �씠由�. */
	private String mname;

	/** �쟾�솕踰덊샇. */
	private String mphone;

	/** �씠硫붿씪. */
	private String memail;

	/** 媛��엯�씪. */
	private java.sql.Date mregdate;

	/** �룷�씤�듃. */
	private int mpoint;

	//암호화 추가
	private String salt;
	/**
	 * �깮�꽦�옄.
	 */
	public MembersVo() {
	}

	public MembersVo(String mid, int gnum, String mpwd, String mname, String mphone, String memail,
			java.sql.Date mregdate, int mpoint) {
		super();
		this.mid = mid;
		this.gnum = gnum;
		this.mpwd = mpwd;
		this.mname = mname;
		this.mphone = mphone;
		this.memail = memail;
		this.mregdate = mregdate;
		this.mpoint = mpoint;
	}
	//salt 추가 생성자 오버로딩
	public MembersVo(String mid, int gnum, String mpwd, String mname, String mphone, String memail, Date mregdate,
			int mpoint, String salt) {
		super();
		this.mid = mid;
		this.gnum = gnum;
		this.mpwd = mpwd;
		this.mname = mname;
		this.mphone = mphone;
		this.memail = memail;
		this.mregdate = mregdate;
		this.mpoint = mpoint;
		this.salt = salt;
	}
	
	
	//salt getter, setter
	

	public String getMid() {
		return mid;
	}


	public String getSalt() {
		return salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public int getGnum() {
		return gnum;
	}

	public void setGnum(int gnum) {
		this.gnum = gnum;
	}

	public String getMpwd() {
		return mpwd;
	}

	public void setMpwd(String mpwd) {
		this.mpwd = mpwd;
	}

	public String getMname() {
		return mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getMphone() {
		return mphone;
	}

	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	public String getMemail() {
		return memail;
	}

	public void setMemail(String memail) {
		this.memail = memail;
	}

	public java.sql.Date getMregdate() {
		return mregdate;
	}

	public void setMregdate(java.sql.Date mregdate) {
		this.mregdate = mregdate;
	}

	public int getMpoint() {
		return mpoint;
	}

	public void setMpoint(int mpoint) {
		this.mpoint = mpoint;
	}
	
	

}
