package test.app.project.vo;

import java.sql.Date;

/**
 * �쉶�썝�뀒�씠釉� 紐⑤뜽 �겢�옒�뒪.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MembersVo{

	private String mid;

	/** �쉶�썝�벑湲됲뀒�씠釉�. */
	private int gnum;

	/** 鍮꾨�踰덊샇. */
	private String mpwd;

	/** �씠由�. */
	private String mname;

	/** �쟾�솕踰덊샇. */
	private String mphone;

	/** �씠硫붿씪. */
	private String memail;

	/** 媛��엯�씪. */
	private java.sql.Date mregdate;

	/** 가입종류. */
	private int login_type;
	
	/* 생성자.
	 */
	public MembersVo(){}
	
	public MembersVo(String mid, int gnum, String mpwd, String mname, String mphone, String memail, Date mregdate,
			int login_type) {

		super();
		this.mid = mid;
		this.gnum = gnum;
		this.mpwd = mpwd;
		this.mname = mname;
		this.mphone = mphone;
		this.memail = memail;
		this.mregdate = mregdate;
		this.login_type = login_type;
	}
	
	public String getMid() {
		return mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public int getGnum() {
		return gnum;
	}

	public void setGnum(int gnum) {
		this.gnum = gnum;
	}

	public String getMpwd() {
		return mpwd;
	}

	public void setMpwd(String mpwd) {
		this.mpwd = mpwd;
	}

	public String getMname() {
		return mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getMphone() {
		return mphone;
	}

	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	public String getMemail() {
		return memail;
	}

	public void setMemail(String memail) {
		this.memail = memail;
	}

	public java.sql.Date getMregdate() {
		return mregdate;
	}

	public void setMregdate(java.sql.Date mregdate) {
		this.mregdate = mregdate;
	}

	public int getLogin_type() {
		return login_type;
	}

	public void setLogin_type(int login_type) {
		this.login_type = login_type;
	}
}
