package test.app.project.vo;


/**
 * 媛앹떎�젙蹂� 紐⑤뜽 �겢�옒�뒪.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomsVo{


	/** 諛⑹떇蹂꾨쾲�샇. */
	private int room_num;

	/** �뾽�냼�뀒�씠釉�. */
	private int house_num;

	/** 媛앹떎紐�. */
	private String roomname;

	/** 媛앹떎媛�寃�. */
	private int room_price;

	/** 媛앹떎�젙蹂�. */
	private String room_info;

	/** 猷몄껜�겕�씤. */
	private int room_check;

	/** 理쒕��씤�썝. */
	private int max_Personnel;

	//추가
	private String company;
	private String house_save_name;
	private String workplace;
	private double avg;
	private String bb;
	/**
	 * �깮�꽦�옄.
	 */
	public RoomsVo() {
	}


	public RoomsVo(int room_num, int house_num, String roomname, int room_price, String room_info, int room_check,
			int max_Personnel) {
		super();
		this.room_num = room_num;
		this.house_num = house_num;
		this.roomname = roomname;
		this.room_price = room_price;
		this.room_info = room_info;
		this.room_check = room_check;
		this.max_Personnel = max_Personnel;
	}


	

	
	public RoomsVo(int room_num, int house_num, String roomname, int room_price, String room_info, int room_check,
			int max_Personnel, String company, String house_save_name, String workplace, double avg, String bb) {
		super();
		this.room_num = room_num;
		this.house_num = house_num;
		this.roomname = roomname;
		this.room_price = room_price;
		this.room_info = room_info;
		this.room_check = room_check;
		this.max_Personnel = max_Personnel;
		this.company = company;
		this.house_save_name = house_save_name;
		this.workplace = workplace;
		this.avg = avg;
		this.bb = bb;
	}

	
	public String getBb() {
		return bb;
	}


	public void setBb(String bb) {
		this.bb = bb;
	}


	public double getAvg() {
		return avg;
	}


	public void setAvg(double avg) {
		this.avg = avg;
	}


	public String getCompany() {
		return company;
	}


	public void setCompany(String company) {
		this.company = company;
	}


	public String getHouse_save_name() {
		return house_save_name;
	}


	public void setHouse_save_name(String house_save_name) {
		this.house_save_name = house_save_name;
	}


	public String getWorkplace() {
		return workplace;
	}


	public void setWorkplace(String workplace) {
		this.workplace = workplace;
	}


	public int getRoom_num() {
		return room_num;
	}


	public void setRoom_num(int room_num) {
		this.room_num = room_num;
	}


	public int getHouse_num() {
		return house_num;
	}


	public void setHouse_num(int house_num) {
		this.house_num = house_num;
	}


	public String getRoomname() {
		return roomname;
	}


	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}


	public int getRoom_price() {
		return room_price;
	}


	public void setRoom_price(int room_price) {
		this.room_price = room_price;
	}


	public String getRoom_info() {
		return room_info;
	}


	public void setRoom_info(String room_info) {
		this.room_info = room_info;
	}


	public int getRoom_check() {
		return room_check;
	}


	public void setRoom_check(int room_check) {
		this.room_check = room_check;
	}


	public int getMax_Personnel() {
		return max_Personnel;
	}


	public void setMax_Personnel(int max_Personnel) {
		this.max_Personnel = max_Personnel;
	}


	@Override
	public String toString() {
		return "RoomsVo [room_num=" + room_num + ", house_num=" + house_num + ", roomname=" + roomname + ", room_price="
				+ room_price + ", room_info=" + room_info + ", room_check=" + room_check + ", max_Personnel="
				+ max_Personnel + ", company=" + company + ", house_save_name=" + house_save_name + ", workplace="
				+ workplace + ", avg=" + avg + ", bb=" + bb + "]";
	}


}
